# Generated by Django 5.2.17 on 2026-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience_starred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail_alt',
        ),
        migrations.AddField(
            model_name='project',
            name='goals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
